# https://upptime.js.org/docs/configuration
owner: jackdbd
repo: uptime-monitors

sites:
  - name: Giacomo Debidda
    url: https://www.giacomodebidda.com/
    method: GET
    assignees:
      - jackdbd

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.giacomodebidda.com
  # cname: uptime-monitors.giacomodebidda.com
  # cname: demo.upptime.js.org
  baseUrl: /uptime-monitors
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitors
  introTitle: "Uptime monitors created with **Upptime**"
  introMessage: This status page uses **real-time** data from the GitHub repository [uptime-monitors](https://github.com/jackdbd/uptime-monitors).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light
