name: 'Send recap to Telegram'

on:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # https://crontab.guru/
    - cron:  '55 20 * * *'
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
    # trigger this workflow manually using the GitHub CLI:
    # gh workflow run "Send recap to Telegram"

jobs:
  send-recap-to-telegram-chat:
    runs-on: ubuntu-latest
    steps:
      - id: response_time_day
        # https://github.com/marketplace/actions/http-request-action
        uses: fjogeleit/http-request-action@v1
        with:
          # url: 'https://raw.githubusercontent.com/jackdbd/uptime-monitors/main/history/summary.json'
          url: 'https://raw.githubusercontent.com/jackdbd/uptime-monitors/main/api/giacomo-debidda/response-time-day.json'
          method: 'GET'

      - id: response_time_week
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://raw.githubusercontent.com/jackdbd/uptime-monitors/main/api/giacomo-debidda/response-time-week.json'
          method: 'GET'

      - id: uptime_month
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://raw.githubusercontent.com/jackdbd/uptime-monitors/main/api/giacomo-debidda/uptime-month.json'
          method: 'GET'

      # - name: Show HTTP response headers
      #   run: echo ${{ steps.response_time_day.outputs.headers }}

      # - name: Show Response
      #   run: |
      #     echo ${{ steps.response_time_day.outputs.response }}

      - name: 💬 send uptime recap to Telegram chat
        # https://github.com/appleboy/telegram-action
        uses: appleboy/telegram-action@v0.1.1
        # This is a container action, so it must run on Linux (it would fail if
        # `runs-on` is either `windows-latest` or `macOS-latest`)
        # https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction
        with:
          to: ${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }}
          token: ${{ secrets.NOTIFICATION_TELEGRAM_BOT_KEY }}
          format: html
          disable_notification: true
          # The Upptime history page contains a <canvas>, and Telegram link unfurling is not able to show it.
          disable_web_page_preview: true
          # https://core.telegram.org/bots/api#formatting-options
          message: |
            <b>📊 Uptime Monitoring recap</b>

            GitHub workflow triggered in repository <a href="${{ github.event.repository.html_url }}">${{ github.event.repository.full_name }}</a>

            ${{ fromJson(steps.response_time_day.outputs.response).label }}: ${{ fromJson(steps.response_time_day.outputs.response).message }}
            ${{ fromJson(steps.response_time_week.outputs.response).label }}: ${{ fromJson(steps.response_time_week.outputs.response).message }}
            ${{ fromJson(steps.uptime_month.outputs.response).label }}: ${{ fromJson(steps.uptime_month.outputs.response).message }}

            <a href="https://status.giacomodebidda.com/history/giacomo-debidda">History</a>
